In [58]:
import pandas as pd

data_paises = pd.read_csv("../InformacionGeneral/Internacional/Detalle_paises.csv")
del data_paises["WORLD_SN"]
del data_paises["ECDC_SN"]
del data_paises["OURWOR_SN"]
del data_paises["JHONH_SN"]
del data_paises["Early_SN"]

data_woldmeter = pd.read_csv("../worldometers.info/worldometers.csv")
columna_woldmeter = data_woldmeter.columns[1:]

for i in columna_woldmeter:
    data_woldmeter[i+"Worldmeter"] = data_woldmeter[i]
    del data_woldmeter[i]
    
merged_left = pd.merge(left=data_paises, right=data_woldmeter, how='left', left_on='WORLDM_Country,Other', right_on='Country,Other')

#data_europa = pd.read_csv("../ecdc.europa/ecdc_europa.csv")
#data_europa
data_ourworld_con = pd.read_csv("../ourworldindata.org/total-cases-covid-19.csv")
data_ourworld_dea = pd.read_csv("../ourworldindata.org/total-deaths-covid-19.csv")
#data_ourworld["Entity"].unique()
#data_ourworld
paises = []
confirmados = []
muertes = []
for i in data_ourworld_con["Entity"].unique():
    maximoConfirmado = max(data_ourworld_con[data_ourworld_con["Entity"] == i]["Total confirmed cases of COVID-19 (cases)"])
    maximoMuerte = max(data_ourworld_dea[data_ourworld_dea["Entity"] == i]["Total confirmed deaths due to COVID-19 (deaths)"])
    #print(i + " " + str(maximo))
    paises.append(i)
    confirmados.append(maximoConfirmado)
    muertes.append(maximoMuerte)

data_ourworld = pd.DataFrame({
    "paises": paises,
    "confirmadoOURWORLD":confirmados,
    "muertosOURWORLD": muertes    
}
)
merged_left = pd.merge(left=merged_left, right=data_ourworld, how='left', left_on='OURWORLD_Entity', right_on='paises')
del merged_left["paises"] 


data_jhon = pd.read_csv("../Johns_Hopkins-covid19/diario/ultimoRegistro.csv")
data_jhon

paises = []
confirmados = []
muertes = []
recuperados = []
activos = []
for i in data_jhon["Country_Region"].unique():
    maximoConfirmado = sum(data_jhon[data_jhon["Country_Region"] == i]["Confirmed"])
    maximoMuerte = sum(data_jhon[data_jhon["Country_Region"] == i]["Deaths"])
    maximoRecuperado = sum(data_jhon[data_jhon["Country_Region"] == i]["Recovered"])
    maximoActivo = sum(data_jhon[data_jhon["Country_Region"] == i]["Active"])
    #print(i + " " + str(maximo))
    paises.append(i)
    confirmados.append(maximoConfirmado)
    muertes.append(maximoMuerte)
    recuperados.append(maximoRecuperado)
    activos.append(maximoActivo)
    
data_jhon_salida = pd.DataFrame({
    "paises": paises,
    "confirmadoJHON":confirmados,
    "muertosJHON": muertes,
    "recuperadosJHON": recuperados,
    "activosJHON": activos
}
)
merged_left = pd.merge(left=merged_left, right=data_jhon_salida, how='left', left_on='JHONH_Country/Region', right_on='paises')
del merged_left["paises"] 
merged_left

,ID,Nombre Español,Nombre Ingles,"WORLDM_Country,Other",ECDC_countriesAndTerritories,OURWORLD_Entity,JHONH_Country/Region,Early_COUNTRY,Tipo,Nombre común,...,Tot Cases/1M popWorldmeter,Deaths/1M popWorldmeter,Reported1st caseWorldmeter,Primer casoWorldmeter,confirmadoOURWORLD,muertosOURWORLD,confirmadoJHON,muertosJHON,recuperadosJHON,activosJHON
0,1,Afganistán,Afghanistan,Afghanistan,Afghanistan,Afghanistan,Afghanistan,Afghanistan,Estado Soberanos,Afganistán,...,7.0,0.20,Feb 23,23-02-2020,235.0,4.0,273.0,6.0,10.0,257.0
1,2,Albania,Albania,Albania,Albania,Albania,Albania,Albania,Estado Soberanos,Albania,...,96.0,6.00,Mar 07,07-03-2020,277.0,16.0,277.0,16.0,76.0,185.0
2,3,Alemania,Germany,Germany,Ghana,Germany,Germany,Germany,Estado Soberanos,Alemania,...,1012.0,13.00,Jan 26,26-01-2020,73522.0,872.0,84794.0,1107.0,22440.0,61247.0
3,4,Andorra,Andorra,Andorra,Andorra,Andorra,Andorra,Andorra,Estado Soberanos,Andorra,...,5539.0,194.00,Mar 01,01-03-2020,428.0,15.0,428.0,15.0,10.0,403.0
4,5,Angola,Angola,Angola,Angola,Angola,Angola,Angola,Estado Soberanos,Angola,...,0.2,0.06,Mar 19,19-03-2020,8.0,2.0,8.0,2.0,1.0,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
230,231,Jersey,Jersey,Jersey,Jersey,Jersey,Jersey,Jersey,Territorio asociado a estados soberanos,Jersey,...,NaN,NaN,NaN,NaN,81.0,2.0,NaN,NaN,NaN,NaN
231,232,Islas Malvinas,Falkland Islands,Falkland Islands,Falkland_Islands_(Malvinas),Falkland Islands,Falkland Islands,Falkland Islands,Territorio asociado a estados soberanos,Islas Malvinas,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
232,233,Crucero Diamond Princess,Diamond Princess,Diamond Princess,Diamond Princess,Diamond Princess,Diamond Princess,Diamond Princess,Otros,Crucero Diamond Princess,...,NaN,NaN,Feb 04,04-02-2020,NaN,NaN,712.0,11.0,619.0,82.0
233,234,Crucero MS Zaandam,MS Zaandam,MS Zaandam,Myanmar,MS Zaandam,MS Zaandam,MS Zaandam,Otros,Crucero MS Zaandam,...,NaN,NaN,Mar 26,26-03-2020,NaN,NaN,9.0,2.0,0.0,7.0
234,235,Casos en un transporte internacional Japón,Cases on an international conveyance Japan,Cases on an international conveyance Japan,Cases_on_an_international_conveyance_Japan,Cases on an international conveyance Japan,Cases on an international conveyance Japan,Cases on an international conveyance Japan,Otros,Casos en un transporte internacional Japón,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [57]:
data_jhon = pd.read_csv("../Johns_Hopkins-covid19/diario/ultimoRegistro.csv")
data_jhon

paises = []
confirmados = []
muertes = []
recuperados = []
activos = []
for i in data_jhon["Country_Region"].unique():
    maximoConfirmado = sum(data_jhon[data_jhon["Country_Region"] == i]["Confirmed"])
    maximoMuerte = sum(data_jhon[data_jhon["Country_Region"] == i]["Deaths"])
    maximoRecuperado = sum(data_jhon[data_jhon["Country_Region"] == i]["Recovered"])
    maximoActivo = sum(data_jhon[data_jhon["Country_Region"] == i]["Active"])
    #print(i + " " + str(maximo))
    paises.append(i)
    confirmados.append(maximoConfirmado)
    muertes.append(maximoMuerte)
    recuperados.append(maximoRecuperado)
    activos.append(maximoActivo)
    
data_jhon_salida = pd.DataFrame({
    "paises": paises,
    "confirmadoJHON":confirmados,
    "muertosJHON": muertes,
    "recuperadosJHON": recuperados,
    "activosJHON": activos
}
)
merged_left = pd.merge(left=merged_left, right=data_jhon_salida, how='left', left_on='JHONH_Country/Region', right_on='paises')
del merged_left["paises"] 
merged_left

KeyError: 'paises'

In [49]:
data_ourworld

          paises  confirmadoOURWORLD  muertosOURWORLD
0    Afghanistan                 235                4
1        Albania                 277               16
2        Algeria                 847               58
3        Andorra                 428               15
4         Angola                   8                2
..           ...                 ...              ...
199    Venezuela                 144                3
200      Vietnam                 239                0
201        World             1000249            51515
202       Zambia                  39                1
203     Zimbabwe                   8                1

[204 rows x 3 columns]