In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("https://raw.githubusercontent.com/MinCiencia/Datos-COVID19/master/input/Covid-19.csv")
data

,Region,Comuna,Poblacion,2020-03-30,2020-04-01,2020-04-03,2020-04-06,2020-04-08,Tasa
0,Arica y Parinacota,Arica,247552,6,6,12,41,63,25.4
1,Arica y Parinacota,Camarones,1233,-,-,-,-,-,0.0
2,Arica y Parinacota,General Lagos,810,-,-,-,-,-,0.0
3,Arica y Parinacota,Putre,2515,-,-,-,-,-,0.0
4,Tarapaca,Alto Hospicio,129999,-,-,-,5,6,4.6
...,...,...,...,...,...,...,...,...,...
341,Magallanes y la Antartica,Punta Arenas,141984,29,87,143,203,207,145.8
342,Magallanes y la Antartica,Rio Verde,211,-,-,-,-,-,0.0
343,Magallanes y la Antartica,San Gregorio,681,-,-,-,-,-,0.0
344,Magallanes y la Antartica,Timaukel,282,-,-,-,-,-,0.0
345,Magallanes y la Antartica,Torres del Paine,1021,-,-,-,-,-,0.0

In [9]:
lista = list(data.iterrows())
data_aux = data
del da
data.columns

Index(['Region', 'Comuna', 'Poblacion', '2020-03-30', '2020-04-01',
       '2020-04-03', '2020-04-06', '2020-04-08', 'Tasa'],
      dtype='object')

In [8]:
for i in lista:
    print(i[1][2])

247552
1233
810
2515
129999
1375
1583
3000
223463
5958
17395
425725
190336
6814
14776
287
10434
1746
13657
28079
5729
19426
13164
171766
14358
7681
11264
14312
57009
11791
9546
13884
256735
32801
4450
249656
23374
32527
121269
4675
12165
4372
29110
29741
15174
20663
53591
16482
25357
29170
15213
45889
17742
14338
19099
8277
1033
25321
37739
49931
26533
68093
23490
19266
7633
6201
10558
20071
17645
97572
167085
36135
11263
96761
20643
83494
16367
11934
315732
139310
361371
7994
7405
109641
28525
88956
142465
180353
139195
36430
172000
40014
206792
112528
142065
40171
100434
402433
122557
189335
100252
126898
330759
124076
103865
104403
134635
578605
14926
141612
250192
74188
82766
107803
101058
266798
30433
157749
253139
645909
254694
136368
190075
160847
334836
103485
18644
133059
11953
86510
503147
81838
21477
96774
15925
37696
14096
7831
21263
22700
36504
3114
26749
6765
7289
59913
14163
7632
27462
19141
6904
14624
13299
6349
11848
14952
20743
17882
9164
3531
13877
265211
63710
30371
78642
50617
41096
44143
9331
22565
50348
9426
163626
4206
10222
6989
101073
32810
60000
49800
44544
9083
8092
8601
11248
21071
14753
16170
19469
46292
49451
9959
236724
30850
4381
17512
19200
22607
198624
33827
5275
16845
28375
12334
5414
11567
8639
11880
4940
18777
12192
6261
56252
4654
16624
12172
5696
18596
6775
4306
38679
30725
37003
91180
238092
6330
125829
33892
11841
97273
26201
23873
27100
22524
218515
45750
31041
27944
10429
49865
4179
10032
145906
3611
14592
14779
158345
11019
58729
15205
22132
56058
25486
12341
26148
18055
18178
7802
8458
25446
12633
15148
40746
24739
11049
7517
10050
6265
33777
82110
7223
26096
29782
12188
10833
12793
302931
15786
10055
19314
35467
30766
59103
5447
15261
39538
10292
17652
20518
7389
23250
20798
35991
32925
176774
42458
36744
47607
5020
16013
4006
4066
15069
12656
20223
2806
9525
18621
17817
14894
173410
1827
269398
9192
48620
4201
21080
11787
5543
29309
8783
8298
14275
7639
10553
25002
5121
5828
3685
61210
1599
920
661
2699
572
137
1983
264
23782
7323
694
141984
211
681
282
1021