In [52]:
import pandas as pd
from datetime import datetime, timedelta
#https://raw.githubusercontent.com/MinCiencia/Datos-COVID19/master/input/Covid-19.csv Principal
#https://raw.githubusercontent.com/MinCiencia/Datos-COVID19/master/output/producto1/Covid-19.csv #Casos totales por comuna incremental:
# Casos totales por comuna
#https://raw.githubusercontent.com/MinCiencia/Datos-COVID19/master/output/producto2/2020-03-30-CasosConfirmados.csv
#https://raw.githubusercontent.com/MinCiencia/Datos-COVID19/master/output/producto2/2020-04-01-CasosConfirmados.csv
#https://raw.githubusercontent.com/MinCiencia/Datos-COVID19/master/output/producto2/2020-04-03-CasosConfirmados.csv
#https://raw.githubusercontent.com/MinCiencia/Datos-COVID19/master/output/producto2/2020-04-06-CasosConfirmados.csv
#https://raw.githubusercontent.com/MinCiencia/Datos-COVID19/master/output/producto2/2020-04-08-CasosConfirmados.csv
#Casos totales por región incremental:
#https://raw.githubusercontent.com/MinCiencia/Datos-COVID19/master/output/producto3/CasosTotalesCumulativo.csv
#Casos totales por región 
#https://raw.githubusercontent.com/MinCiencia/Datos-COVID19/master/output/producto4/2020-03-03-CasosConfirmados-totalRegional.csv
#...
#https://raw.githubusercontent.com/MinCiencia/Datos-COVID19/master/output/producto4/2020-04-09-CasosConfirmados-totalRegional.csv
#Casos totales recuperados
# https://raw.githubusercontent.com/MinCiencia/Datos-COVID19/master/output/producto5/recuperados.csv

def realizarColumna(data, largo):
    lista = list(data.iterrows())
    data_aux = data
    try:
        del data_aux["Tasa"]
    except:
        pass
    data_aux.columns
    salida = []
    for i in lista:
        #print(i[1])
        try:
            aux = {"Region":i[1]["Region"],"Comuna":i[1]["Comuna"],"Poblacion":i[1]["Poblacion"],"Tasa":i[1]["Tasa"]}
        except:
            aux = {"Region":i[1]["Region"],"Comuna":i[1]["Comuna"],"Poblacion":i[1]["Poblacion"]}
        for j in data_aux.columns[largo:]:
            entrada = aux.copy()
            #entrada[j] = 
            entrada["Fecha"] = i[1][j]
            salida.append(entrada.copy())

    return pd.DataFrame(salida) 

def realizarColumnaParticular(data, key):
    lista = list(data.iterrows())
    data_aux = data
    data_aux.columns
    salida = []
    for i in lista:
        #print(i[1])
        aux = {key:i[1][key]}
        for j in data_aux.columns[1:]:
            entrada = aux.copy()
            #entrada[j] = 
            entrada["Fecha"] = i[1][j]
            salida.append(entrada.copy())

    return pd.DataFrame(salida)
url = "https://raw.githubusercontent.com/MinCiencia/Datos-COVID19/master/input/Covid-19.csv"
data = realizarColumna(pd.read_csv(url),3)
data.to_csv("Principal.csv", index=False)

url = "https://raw.githubusercontent.com/MinCiencia/Datos-COVID19/master/output/producto1/Covid-19.csv"
data = realizarColumna(pd.read_csv(url),3)
data.to_csv("Producto1.csv", index=False)

salida = []
inicio = datetime(2020,3,30)
fin    = datetime.now()
url = "https://raw.githubusercontent.com/MinCiencia/Datos-COVID19/master/output/producto2/"  #2020-03-30-CasosConfirmados.csv
lista_fechas = [inicio + timedelta(days=d) for d in range((fin - inicio).days + 1)] 
for i in lista_fechas:
    try:
        data = pd.read_csv(url + i.strftime("%Y-%m-%d-CasosConfirmados.csv"))
        data["Fecha"] = i.strftime("%d-%m-%Y")
        salida.append(data)
    except:
        pass
    
data =pd.concat(salida)
data.to_csv("Producto2.csv", index=False)

url = "https://raw.githubusercontent.com/MinCiencia/Datos-COVID19/master/output/producto3/CasosTotalesCumulativo.csv"
data = realizarColumnaParticular(pd.read_csv(url),"Region")
data.to_csv("Producto3.csv", index=False)

salida = []
inicio = datetime(2020,3,3)
fin    = datetime.now()

url = "https://raw.githubusercontent.com/MinCiencia/Datos-COVID19/master/output/producto4/"  #2020-03-03-CasosConfirmados-totalRegional.csv
lista_fechas = [inicio + timedelta(days=d) for d in range((fin - inicio).days + 1)] 
for i in lista_fechas:
    try:
        data = pd.read_csv(url + i.strftime("%Y-%m-%d-CasosConfirmados-totalRegional.csv"))
        data["Fecha"] = i.strftime("%d-%m-%Y")
        salida.append(data)
    except:
        pass
data =pd.concat(salida)
data.to_csv("Producto4.csv", index=False)

url = "https://raw.githubusercontent.com/MinCiencia/Datos-COVID19/master/output/producto3/CasosTotalesCumulativo.csv"
data = realizarColumnaParticular(pd.read_csv(url),"Region")
data.to_csv("Producto3.csv", index=False)

In [37]:
url = "https://raw.githubusercontent.com/MinCiencia/Datos-COVID19/master/output/producto2/"  #2020-03-30-CasosConfirmados.csv

(1730, 5)

In [53]:
data = pd.read_csv("Producto4.csv")
data

,Region,Casos nuevos,Casos totales,Casos recuperados,Fecha,Casos nuevos,Casos totales,Fallecidos,Región,Casos fallecidos,% Casos totales**
0,Arica y Parinacota,0.0,0.0,0.0,03-03-2020,NaN,NaN,NaN,NaN,NaN,NaN
1,Tarapaca,0.0,0.0,0.0,03-03-2020,NaN,NaN,NaN,NaN,NaN,NaN
2,Antofagasta,0.0,0.0,0.0,03-03-2020,NaN,NaN,NaN,NaN,NaN,NaN
3,Atacama,0.0,0.0,0.0,03-03-2020,NaN,NaN,NaN,NaN,NaN,NaN
4,Coquimbo,0.0,0.0,0.0,03-03-2020,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
658,Los Rios,NaN,NaN,NaN,10-04-2020,6.0,124.0,2.0,NaN,NaN,1.91 %
659,Los Lagos,NaN,NaN,NaN,10-04-2020,9.0,349.0,2.0,NaN,NaN,5.37 %
660,Aysen,NaN,NaN,NaN,10-04-2020,0.0,7.0,0.0,NaN,NaN,0.11 %
661,Magallanes,NaN,NaN,NaN,10-04-2020,45.0,331.0,3.0,NaN,NaN,5.09 %
662,Total,NaN,NaN,NaN,10-04-2020,529.0,6501.0,65.0,NaN,NaN,100%

In [20]:
data_final = pd.DataFrame(salida)
data_final

                         Region            Comuna  Poblacion Fecha
0            Arica y Parinacota             Arica     247552     6
1            Arica y Parinacota             Arica     247552     6
2            Arica y Parinacota             Arica     247552    12
3            Arica y Parinacota             Arica     247552    41
4            Arica y Parinacota             Arica     247552    63
...                         ...               ...        ...   ...
1725  Magallanes y la Antartica  Torres del Paine       1021     -
1726  Magallanes y la Antartica  Torres del Paine       1021     -
1727  Magallanes y la Antartica  Torres del Paine       1021     -
1728  Magallanes y la Antartica  Torres del Paine       1021     -
1729  Magallanes y la Antartica  Torres del Paine       1021     -

[1730 rows x 4 columns]